### ISSUE TITLE
miniconda docker image cannot run jupyter as documented on hub

### ISSUE THREAD

**Issue by gboeing** [ContinuumIO/docker-images#127]
On Docker Hub it says to run Jupyter notebook via the miniconda image with the following command:

```
docker run -i -t -p 8888:8888 continuumio/miniconda /bin/bash -c "/opt/conda/bin/conda install jupyter -y --quiet && mkdir /opt/notebooks && /opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='*' --port=8888 --no-browser"
```

But it produces an error: `socket.gaierror: [Errno -2] Name or service not known`

Here's the full command execution output:

```
C:\>docker run -i -t -p 8888:8888 continuumio/miniconda /bin/bash -c "/opt/conda/bin/conda install jupyter -y --quiet && mkdir /opt/notebooks && /opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='*' --port=8888 --no-browser"
Collecting package metadata: ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /opt/conda

  added / updated specs:
    - jupyter


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    attrs-19.1.0               |           py27_1          56 KB
    backports-1.0              |           py27_1           3 KB
    backports.shutil_get_terminal_size-1.0.0|           py27_2           8 KB
    backports_abc-0.5          |   py27h7b3c97b_0          12 KB
    bleach-3.1.0               |           py27_0         228 KB
    configparser-3.7.4         |           py27_0          41 KB
    dbus-1.13.6                |       h746ee38_0         587 KB
    decorator-4.4.0            |           py27_1          18 KB
    defusedxml-0.6.0           |             py_0          23 KB
    entrypoints-0.3            |           py27_0          12 KB
    expat-2.2.6                |       he6710b0_0         187 KB
    fontconfig-2.13.0          |       h9420a91_0         291 KB
    freetype-2.9.1             |       h8a8886c_1         822 KB
    functools32-3.2.3.2        |           py27_1          23 KB
    glib-2.56.2                |       hd408876_0         5.0 MB
    gmp-6.1.2                  |       h6c8ec71_1         744 KB
    gst-plugins-base-1.14.0    |       hbbd80ab_1         6.3 MB
    gstreamer-1.14.0           |       hb453b48_1         3.8 MB
    icu-58.2                   |       h9c2bf20_1        22.5 MB
    ipykernel-4.10.0           |           py27_0         145 KB
    ipython-5.8.0              |           py27_0         1.0 MB
    ipython_genutils-0.2.0     |   py27h89fb69b_0          38 KB
    ipywidgets-7.4.2           |           py27_0         148 KB
    jinja2-2.10.1              |           py27_0         181 KB
    jpeg-9b                    |       h024ee3a_2         248 KB
    jsonschema-3.0.1           |           py27_0          86 KB
    jupyter-1.0.0              |           py27_7           6 KB
    jupyter_client-5.2.4       |           py27_0         125 KB
    jupyter_console-5.2.0      |           py27_1          35 KB
    jupyter_core-4.4.0         |           py27_0          62 KB
    libpng-1.6.37              |       hbc83047_0         364 KB
    libsodium-1.0.16           |       h1bed415_0         302 KB
    libuuid-1.0.3              |       h1bed415_2          16 KB
    libxcb-1.13                |       h1bed415_1         502 KB
    libxml2-2.9.9              |       he19cac6_0         2.0 MB
    markupsafe-1.1.1           |   py27h7b6447c_0          29 KB
    mistune-0.8.4              |   py27h7b6447c_0          53 KB
    nbconvert-5.5.0            |             py_0         381 KB
    nbformat-4.4.0             |           py27_0         139 KB
    notebook-5.7.8             |           py27_0         7.2 MB
    pandoc-2.2.3.2             |                0        20.8 MB
    pandocfilters-1.4.2        |           py27_1          13 KB
    pathlib2-2.3.3             |           py27_0          31 KB
    pcre-8.43                  |       he6710b0_0         260 KB
    pexpect-4.7.0              |           py27_0          80 KB
    pickleshare-0.7.5          |           py27_0          12 KB
    prometheus_client-0.6.0    |           py27_0          69 KB
    prompt_toolkit-1.0.15      |           py27_0         333 KB
    ptyprocess-0.6.0           |           py27_0          22 KB
    pygments-2.3.1             |           py27_0         1.4 MB
    pyqt-5.9.2                 |   py27h05f1152_2         5.4 MB
    pyrsistent-0.14.11         |   py27h7b6447c_0          88 KB
    python-dateutil-2.8.0      |           py27_0         279 KB
    pyzmq-18.0.0               |   py27he6710b0_0         463 KB
    qt-5.9.7                   |       h5867ecd_1        85.9 MB
    qtconsole-4.4.3            |           py27_0         155 KB
    scandir-1.10.0             |   py27h7b6447c_0          32 KB
    send2trash-1.5.0           |           py27_0          16 KB
    simplegeneric-0.8.1        |           py27_2           9 KB
    singledispatch-3.4.0.3     |           py27_0          15 KB
    sip-4.19.8                 |   py27hf484d3e_0         291 KB
    terminado-0.8.2            |           py27_0          22 KB
    testpath-0.4.2             |           py27_0          91 KB
    tornado-5.1.1              |   py27h7b6447c_0         643 KB
    traitlets-4.3.2            |           py27_0         128 KB
    wcwidth-0.1.7              |   py27h9e3e1ab_0          25 KB
    webencodings-0.5.1         |           py27_1          19 KB
    widgetsnbextension-3.4.2   |           py27_0         1.7 MB
    xz-5.2.4                   |       h14c3975_4         366 KB
    zeromq-4.3.1               |       he6710b0_3         666 KB
    ------------------------------------------------------------
                                           Total:       172.7 MB

The following NEW packages will be INSTALLED:

  attrs              pkgs/main/linux-64::attrs-19.1.0-py27_1
  backports          pkgs/main/linux-64::backports-1.0-py27_1
  backports.shutil_~ pkgs/main/linux-64::backports.shutil_get_terminal_size-1.0.0-py27_2
  backports_abc      pkgs/main/linux-64::backports_abc-0.5-py27h7b3c97b_0
  bleach             pkgs/main/linux-64::bleach-3.1.0-py27_0
  configparser       pkgs/main/linux-64::configparser-3.7.4-py27_0
  dbus               pkgs/main/linux-64::dbus-1.13.6-h746ee38_0
  decorator          pkgs/main/linux-64::decorator-4.4.0-py27_1
  defusedxml         pkgs/main/noarch::defusedxml-0.6.0-py_0
  entrypoints        pkgs/main/linux-64::entrypoints-0.3-py27_0
  expat              pkgs/main/linux-64::expat-2.2.6-he6710b0_0
  fontconfig         pkgs/main/linux-64::fontconfig-2.13.0-h9420a91_0
  freetype           pkgs/main/linux-64::freetype-2.9.1-h8a8886c_1
  functools32        pkgs/main/linux-64::functools32-3.2.3.2-py27_1
  glib               pkgs/main/linux-64::glib-2.56.2-hd408876_0
  gmp                pkgs/main/linux-64::gmp-6.1.2-h6c8ec71_1
  gst-plugins-base   pkgs/main/linux-64::gst-plugins-base-1.14.0-hbbd80ab_1
  gstreamer          pkgs/main/linux-64::gstreamer-1.14.0-hb453b48_1
  icu                pkgs/main/linux-64::icu-58.2-h9c2bf20_1
  ipykernel          pkgs/main/linux-64::ipykernel-4.10.0-py27_0
  ipython            pkgs/main/linux-64::ipython-5.8.0-py27_0
  ipython_genutils   pkgs/main/linux-64::ipython_genutils-0.2.0-py27h89fb69b_0
  ipywidgets         pkgs/main/linux-64::ipywidgets-7.4.2-py27_0
  jinja2             pkgs/main/linux-64::jinja2-2.10.1-py27_0
  jpeg               pkgs/main/linux-64::jpeg-9b-h024ee3a_2
  jsonschema         pkgs/main/linux-64::jsonschema-3.0.1-py27_0
  jupyter            pkgs/main/linux-64::jupyter-1.0.0-py27_7
  jupyter_client     pkgs/main/linux-64::jupyter_client-5.2.4-py27_0
  jupyter_console    pkgs/main/linux-64::jupyter_console-5.2.0-py27_1
  jupyter_core       pkgs/main/linux-64::jupyter_core-4.4.0-py27_0
  libpng             pkgs/main/linux-64::libpng-1.6.37-hbc83047_0
  libsodium          pkgs/main/linux-64::libsodium-1.0.16-h1bed415_0
  libuuid            pkgs/main/linux-64::libuuid-1.0.3-h1bed415_2
  libxcb             pkgs/main/linux-64::libxcb-1.13-h1bed415_1
  libxml2            pkgs/main/linux-64::libxml2-2.9.9-he19cac6_0
  markupsafe         pkgs/main/linux-64::markupsafe-1.1.1-py27h7b6447c_0
  mistune            pkgs/main/linux-64::mistune-0.8.4-py27h7b6447c_0
  nbconvert          pkgs/main/noarch::nbconvert-5.5.0-py_0
  nbformat           pkgs/main/linux-64::nbformat-4.4.0-py27_0
  notebook           pkgs/main/linux-64::notebook-5.7.8-py27_0
  pandoc             pkgs/main/linux-64::pandoc-2.2.3.2-0
  pandocfilters      pkgs/main/linux-64::pandocfilters-1.4.2-py27_1
  pathlib2           pkgs/main/linux-64::pathlib2-2.3.3-py27_0
  pcre               pkgs/main/linux-64::pcre-8.43-he6710b0_0
  pexpect            pkgs/main/linux-64::pexpect-4.7.0-py27_0
  pickleshare        pkgs/main/linux-64::pickleshare-0.7.5-py27_0
  prometheus_client  pkgs/main/linux-64::prometheus_client-0.6.0-py27_0
  prompt_toolkit     pkgs/main/linux-64::prompt_toolkit-1.0.15-py27_0
  ptyprocess         pkgs/main/linux-64::ptyprocess-0.6.0-py27_0
  pygments           pkgs/main/linux-64::pygments-2.3.1-py27_0
  pyqt               pkgs/main/linux-64::pyqt-5.9.2-py27h05f1152_2
  pyrsistent         pkgs/main/linux-64::pyrsistent-0.14.11-py27h7b6447c_0
  python-dateutil    pkgs/main/linux-64::python-dateutil-2.8.0-py27_0
  pyzmq              pkgs/main/linux-64::pyzmq-18.0.0-py27he6710b0_0
  qt                 pkgs/main/linux-64::qt-5.9.7-h5867ecd_1
  qtconsole          pkgs/main/linux-64::qtconsole-4.4.3-py27_0
  scandir            pkgs/main/linux-64::scandir-1.10.0-py27h7b6447c_0
  send2trash         pkgs/main/linux-64::send2trash-1.5.0-py27_0
  simplegeneric      pkgs/main/linux-64::simplegeneric-0.8.1-py27_2
  singledispatch     pkgs/main/linux-64::singledispatch-3.4.0.3-py27_0
  sip                pkgs/main/linux-64::sip-4.19.8-py27hf484d3e_0
  terminado          pkgs/main/linux-64::terminado-0.8.2-py27_0
  testpath           pkgs/main/linux-64::testpath-0.4.2-py27_0
  tornado            pkgs/main/linux-64::tornado-5.1.1-py27h7b6447c_0
  traitlets          pkgs/main/linux-64::traitlets-4.3.2-py27_0
  wcwidth            pkgs/main/linux-64::wcwidth-0.1.7-py27h9e3e1ab_0
  webencodings       pkgs/main/linux-64::webencodings-0.5.1-py27_1
  widgetsnbextension pkgs/main/linux-64::widgetsnbextension-3.4.2-py27_0
  xz                 pkgs/main/linux-64::xz-5.2.4-h14c3975_4
  zeromq             pkgs/main/linux-64::zeromq-4.3.1-he6710b0_3


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
[I 15:26:19.206 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python2.7/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/lib/python2.7/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "</opt/conda/lib/python2.7/site-packages/decorator.pyc:decorator-gen-7>", line 2, in initialize
  File "/opt/conda/lib/python2.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python2.7/site-packages/notebook/notebookapp.py", line 1630, in initialize
    self.init_webapp()
  File "/opt/conda/lib/python2.7/site-packages/notebook/notebookapp.py", line 1378, in init_webapp
    self.jinja_environment_options,
  File "/opt/conda/lib/python2.7/site-packages/notebook/notebookapp.py", line 159, in __init__
    default_url, settings_overrides, jinja_env_options)
  File "/opt/conda/lib/python2.7/site-packages/notebook/notebookapp.py", line 252, in init_settings
    allow_remote_access=jupyter_app.allow_remote_access,
  File "/opt/conda/lib/python2.7/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/opt/conda/lib/python2.7/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/opt/conda/lib/python2.7/site-packages/notebook/notebookapp.py", line 867, in _default_allow_remote
    for info in socket.getaddrinfo(self.ip, self.port, 0, socket.SOCK_STREAM):
socket.gaierror: [Errno -2] Name or service not known
```

**Comment by gboeing** [comment]
I believe you just need to change `--ip='*'` to `--ip='0.0.0.0'` to fix this.

**Comment by Chichilele** [comment]
Same issue, try adding an address and allowing root like this:
`docker run -i -t -p 8888:8888 continuumio/anaconda3 /bin/bash -c "/opt/conda/bin/conda install jupyter -y --quiet && mkdir /opt/notebooks && /opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='0.0.0.0' --port=8888 --no-browser --allow-root"`
