### ISSUE TITLE
miniconda3 missing bash on alpine

### ISSUE THREAD

**Issue by OrangeDog** [ContinuumIO/docker-images#159]
Using `continuumio/miniconda3:4.7.12-alpine`, with no mention of bash in my code or recipe:

```
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 449, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 440, in execute
    verify=args.verify, variants=args.variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 2339, in build_tree
    notest=notest,
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 1487, in build
    cwd=src_dir, stats=build_stats)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/utils.py", line 399, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/utils.py", line 374, in _func_defaulting_env_to_os_environ
    proc = PopenWrapper(_args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/utils.py", line 259, in __init__
    self.out, self.err = self._execute(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/utils.py", line 285, in _execute
    _popen = psutil.Popen(*args, **kwargs) if psutil else subprocess.Popen(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/psutil/__init__.py", line 1431, in __init__
    self.__subproc = subprocess.Popen(*args, **kwargs)
  File "/opt/conda/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/opt/conda/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/bin/bash': '/bin/bash'
```

You'll need `RUN apk add --no-cache bash` or similar.

**Comment by mingwandroid** [comment]
@msarahan, could we do anything with virtual packages here to represent a system `bash` having been found so conda-build could depend on `bash`?

**Comment by bsolomon1124** [comment]
Standard shell on Alpine is `ash`, so yes, this install should probably be required.

**Comment by alanhoyle** [comment]
`bash` is also a requirement for nextflow workflows  #196 #197

**Comment by dbast** [comment]
This got added in the last release, thus closing.
