### ISSUE TITLE
PermissionError for pip install

### ISSUE THREAD

**Issue by jawang35** [ContinuumIO/docker-images#192]
Creating an environment with `pip` dependencies in `alpine` fails on a `PermissionError`.

environment.yml:
```YAML
name: sample-environment
channels:
  - conda-forge
  - defaults
dependencies:
  - autoflake=1.3
  - black=19.3b0
  - flake8=3.7.9
  - h5py=2.10.0
  - isort=4.3.21
  - make=4.2.1
  - mypy=0.711
  - numpy=1.17.3
  - pip=19.1.1
  - pytest=5.0.1
  - python=3.7.3
  - scipy=1.4.1
  - pip:
    - tensorflow==2.1.0rc0
```

Dockerfile:
```Dockerfile
FROM continuumio/miniconda3:4.9.2-alpine

SHELL ["sh", "--login", "-c"]
WORKDIR /opt/app

COPY environment.yml .
RUN conda env create --file environment.yml
```

Output:
```
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

Downloading and Extracting Packages
libgfortran4-7.5.0   | 1.3 MB    | ########## | 100%
readline-8.0         | 281 KB    | ########## | 100%
zipp-3.4.0           | 11 KB     | ########## | 100%
libcblas-3.9.0       | 11 KB     | ########## | 100%
mypy-0.711           | 951 KB    | ########## | 100%
libev-4.33           | 104 KB    | ########## | 100%
black-19.3b0         | 76 KB     | ########## | 100%
libnghttp2-1.41.0    | 774 KB    | ########## | 100%
libstdcxx-ng-9.3.0   | 4.0 MB    | ########## | 100%
setuptools-49.6.0    | 944 KB    | ########## | 100%
py-1.9.0             | 74 KB     | ########## | 100%
libffi-3.2.1         | 47 KB     | ########## | 100%
xz-5.2.5             | 343 KB    | ########## | 100%
wheel-0.36.0         | 30 KB     | ########## | 100%
wcwidth-0.2.5        | 33 KB     | ########## | 100%
libedit-3.1.20191231 | 121 KB    | ########## | 100%
pytest-5.0.1         | 347 KB    | ########## | 100%
isort-4.3.21         | 64 KB     | ########## | 100%
mccabe-0.6.1         | 8 KB      | ########## | 100%
appdirs-1.4.4        | 13 KB     | ########## | 100%
click-7.1.2          | 64 KB     | ########## | 100%
krb5-1.17.2          | 1.4 MB    | ########## | 100%
hdf5-1.10.6          | 3.1 MB    | ########## | 100%
libgfortran-ng-7.5.0 | 22 KB     | ########## | 100%
importlib-metadata-3 | 12 KB     | ########## | 100%
backports-1.0        | 4 KB      | ########## | 100%
psutil-5.7.3         | 339 KB    | ########## | 100%
zlib-1.2.11          | 106 KB    | ########## | 100%
packaging-20.4       | 32 KB     | ########## | 100%
pyflakes-2.1.1       | 49 KB     | ########## | 100%
c-ares-1.17.1        | 111 KB    | ########## | 100%
ld_impl_linux-64-2.3 | 617 KB    | ########## | 100%
atomicwrites-1.4.0   | 10 KB     | ########## | 100%
scipy-1.4.1          | 18.8 MB   | ########## | 100%
openssl-1.1.1h       | 2.1 MB    | ########## | 100%
importlib_metadata-3 | 3 KB      | ########## | 100%
pluggy-0.13.1        | 29 KB     | ########## | 100%
sqlite-3.33.0        | 1.4 MB    | ########## | 100%
entrypoints-0.3      | 8 KB      | ########## | 100%
libcurl-7.71.1       | 312 KB    | ########## | 100%
ncurses-6.2          | 985 KB    | ########## | 100%
tk-8.6.10            | 3.2 MB    | ########## | 100%
_openmp_mutex-4.5    | 22 KB     | ########## | 100%
python_abi-3.7       | 4 KB      | ########## | 100%
_libgcc_mutex-0.1    | 3 KB      | ########## | 100%
certifi-2020.11.8    | 150 KB    | ########## | 100%
attrs-20.3.0         | 41 KB     | ########## | 100%
pip-19.1.1           | 1.8 MB    | ########## | 100%
make-4.2.1           | 458 KB    | ########## | 100%
h5py-2.10.0          | 1.1 MB    | ########## | 100%
backports.functools_ | 8 KB      | ########## | 100%
libopenblas-0.3.12   | 8.2 MB    | ########## | 100%
autoflake-1.3        | 14 KB     | ########## | 100%
flake8-3.7.9         | 128 KB    | ########## | 100%
mypy_extensions-0.4. | 10 KB     | ########## | 100%
ca-certificates-2020 | 145 KB    | ########## | 100%
libblas-3.9.0        | 11 KB     | ########## | 100%
liblapack-3.9.0      | 11 KB     | ########## | 100%
libssh2-1.9.0        | 225 KB    | ########## | 100%
libgomp-9.3.0        | 378 KB    | ########## | 100%
python-3.7.3         | 35.3 MB   | ########## | 100%
bzip2-1.0.8          | 484 KB    | ########## | 100%
more-itertools-8.6.0 | 37 KB     | ########## | 100%
pycodestyle-2.5.0    | 36 KB     | ########## | 100%
libgcc-ng-9.3.0      | 7.8 MB    | ########## | 100%
pyparsing-2.4.7      | 60 KB     | ########## | 100%
six-1.15.0           | 14 KB     | ########## | 100%
toml-0.10.2          | 18 KB     | ########## | 100%
typed-ast-1.4.1      | 206 KB    | ########## | 100%
numpy-1.17.3         | 5.1 MB    | ########## | 100%
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Installing pip dependencies: ...working... failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/opt/conda/lib/python3.8/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/opt/conda/lib/python3.8/site-packages/conda_env/cli/main_create.py", line 118, in execute
        result[installer_type] = installer.install(prefix, pkg_specs, args, env)
      File "/opt/conda/lib/python3.8/site-packages/conda_env/installers/pip.py", line 70, in install
        return _pip_install_via_requirements(*args, **kwargs)
      File "/opt/conda/lib/python3.8/site-packages/conda_env/installers/pip.py", line 44, in _pip_install_via_requirements
        requirements = Utf8NamedTemporaryFile(mode='w',
      File "/opt/conda/lib/python3.8/site-packages/conda/_vendor/auxlib/compat.py", line 81, in Utf8NamedTemporaryFile
        return NamedTemporaryFile(mode=mode, buffering=buffering, encoding=encoding,
      File "/opt/conda/lib/python3.8/tempfile.py", line 541, in NamedTemporaryFile
        (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
      File "/opt/conda/lib/python3.8/tempfile.py", line 250, in _mkstemp_inner
        fd = _os.open(file, flags, 0o600)
    PermissionError: [Errno 13] Permission denied: '/opt/app/condaenv.wfu4h0fj.requirements.txt'

`$ /opt/conda/bin/conda-env create --file environment.yml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/opt/conda/bin/conda
                CONDA_MD5=122c8c9beb51e124ab32a0fa6426c656
             CONDA_PREFIX=/opt/conda
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/opt/conda/bin/python
               CONDA_ROOT=/opt/conda
              CONDA_SHLVL=1
            CONDA_VERSION=4.9.2
           CURL_CA_BUNDLE=<not set>
                     PATH=/opt/conda/bin:/opt/conda/condabin:/usr/local/sbin:/usr/local/bin:/usr
                          /sbin:/usr/bin:/sbin:/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /home/anaconda/.condarc
 populated config files :
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __glibc=2.28=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/conda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /home/anaconda/.conda/pkgs
       envs directories : /opt/conda/envs
                          /home/anaconda/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.5 Linux/5.4.39-linuxkit alpine/3.9.6 glibc/2.28
                UID:GID : 10151:101
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

The command 'sh --login -c /opt/conda/bin/conda env create --file environment.yml' returned a non-zero code: 1
```

**Comment by chenghlee** [comment]
That's because the  Alpine miniconda3 images run a non-root (`anaconda`) user. I'm not convinced that makes sense for this sort of image, so I'll be pushing an updated 4.9.2 image later today without this restriction.

**Comment by jawang35** [comment]
This works now with your fix. Thanks!
