### ISSUE TITLE
Cannot run  the spyder after  download this  images for anaconda  

### ISSUE THREAD

**Issue by jluite** [ContinuumIO/docker-images#24]
After downloaded and run docker  image of anconda followed by bash command as " sudo docker pull continuumio/anaconda " and "sudo docker run -i -t continuumio/anaconda /bin/bash"  respectively , I want to run bash command like " spyder" . But it indicates " Traceback (most recent call last):
  File "/opt/conda/bin/spyder", line 2, in <module>
    from spyderlib import start_app
  File "/opt/conda/lib/python2.7/site-packages/spyderlib/start_app.py", line 12, in <module>
    from spyderlib.baseconfig import get_conf_path, running_in_mac_app
  File "/opt/conda/lib/python2.7/site-packages/spyderlib/baseconfig.py", line 188, in <module>
    from spyderlib.otherplugins import PLUGIN_PATH
  File "/opt/conda/lib/python2.7/site-packages/spyderlib/otherplugins.py", line 17, in <module>
    from spyderlib.utils import programs
  File "/opt/conda/lib/python2.7/site-packages/spyderlib/utils/programs.py", line 29, in <module>
    username = encoding.to_unicode_from_fs(os.environ.get('USER'))
  File "/opt/conda/lib/python2.7/site-packages/spyderlib/utils/encoding.py", line 62, in to_unicode_from_fs
    string = to_text_string(string.toUtf8(), 'utf-8')
AttributeError: 'NoneType' object has no attribute 'toUtf8'  "

Any suggestion is appreciated , Thanks  alot.

**Comment by stefanborchardt** [comment]
Can confirm this for Google's container-vm.

**Comment by koverholt** [comment]
The error you're seeing here is because the `$USER` environment variable is not set. If I run with `sudo docker run -e USER=root -i -t continuumio/anaconda /bin/bash` and run `spyder`, then I get an error related to the X server (I'm running on OS X):

```
# spyder
Spyder: cannot connect to X server
```

It looks like you'll need to do some extra configuration steps (specific to your setup) to work with GUI apps inside of the container, see [here](http://fabiorehm.com/blog/2014/09/11/running-gui-apps-with-docker/) and [here](http://wiki.ros.org/docker/Tutorials/GUI).
