### ISSUE TITLE
note book is not working in anaconda

### ISSUE THREAD

**Issue by salwa609** [ContinuumIO/docker-images#450]
Traceback (most recent call last):
File "C:\Users\DELL\anaconda3\Lib\site-packages\notebook\traittypes.py", line 235, in _resolve_classes
klass = self._resolve_string(klass)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\DELL\AppData\Roaming\Python\Python311\site-packages\traitlets\traitlets.py", line 2009, in _resolve_string
return import_item(string)
^^^^^^^^^^^^^^^^^^^
File "C:\Users\DELL\AppData\Roaming\Python\Python311\site-packages\traitlets\utils\importstring.py", line 30, in import_item
module = __import__(package, fromlist=[obj])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'jupyter_server.contents'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\DELL\anaconda3\Scripts\jupyter-notebook-script.py", line 10, in 
sys.exit(main())
^^^^^^
File "C:\Users\DELL\AppData\Roaming\Python\Python311\site-packages\jupyter_core\application.py", line 285, in launch_instance
return super().launch_instance(argv=argv, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\DELL\AppData\Roaming\Python\Python311\site-packages\traitlets\config\application.py", line 1044, in launch_instance
app = cls.instance(**kwargs)
^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\DELL\AppData\Roaming\Python\Python311\site-packages\traitlets\config\configurable.py", line 555, in instance
inst = cls(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^
File "C:\Users\DELL\AppData\Roaming\Python\Python311\site-packages\traitlets\traitlets.py", line 1295, in __new__
inst.setup_instance(*args, **kwargs)
File "C:\Users\DELL\AppData\Roaming\Python\Python311\site-packages\traitlets\traitlets.py", line 1338, in setup_instance
super(HasTraits, self).setup_instance(*args, **kwargs)
File "C:\Users\DELL\AppData\Roaming\Python\Python311\site-packages\traitlets\traitlets.py", line 1314, in setup_instance
init(self)
File "C:\Users\DELL\anaconda3\Lib\site-packages\notebook\traittypes.py", line 226, in instance_init
self._resolve_classes()
File "C:\Users\DELL\anaconda3\Lib\site-packages\notebook\traittypes.py", line 238, in _resolve_classes
warn(f"{klass} is not importable. Is it installed?", ImportWarning)
TypeError: warn() missing 1 required keyword-only argument: 'stacklevel'

**Comment by dbast** [comment]
@salwa609 Looks like a local Anaconda3 installation... how does this report relate to the docker-images repo? Feel free to report this here https://github.com/ContinuumIO/anaconda-issues/issues
