### ISSUE TITLE
pyplot not available - anaconda3:5.0.1

### ISSUE THREAD

**Issue by samhatchett** [ContinuumIO/docker-images#76]
could be regression of #8 and certainly related to #49 

```
$ docker run -it continuumio/anaconda3:latest python -c '\
> import matplotlib; \
> import matplotlib.pyplot as plt; \
> '
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/opt/conda/lib/python3.6/site-packages/matplotlib/pyplot.py", line 113, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/opt/conda/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 60, in pylab_setup
    [backend_name], 0)
  File "/opt/conda/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 16, in <module>
    from .backend_qt5 import (
  File "/opt/conda/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 18, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "/opt/conda/lib/python3.6/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 20, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "/opt/conda/lib/python3.6/site-packages/matplotlib/backends/qt_editor/formlayout.py", line 56, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "/opt/conda/lib/python3.6/site-packages/matplotlib/backends/qt_compat.py", line 137, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

**Comment by dbast** [comment]
This works with newer releases e.g. continuumio/anaconda3:latest. Thus closing, please reopen, if that still is an issue.
