### ISSUE TITLE
AttributeError: type object 'IOLoop' has no attribute 'initialized'

### ISSUE THREAD

**Issue by znmeb** [ContinuumIO/docker-images#80]
How to reproduce:

```
$ docker run -i -t -p 8888:8888 continuumio/miniconda3 /bin/bash -c "/opt/conda/bin/conda install jupyter -y --quiet && mkdir /opt/notebooks && /opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='*' --port=8888 --no-browser"
Solving environment: ...working... done


==> WARNING: A newer version of conda exists. <==
  current version: 4.4.10
  latest version: 4.4.11

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /opt/conda

  added / updated specs: 
    - jupyter


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    send2trash-1.5.0           |           py36_0          16 KB
    icu-58.2                   |       h9c2bf20_1        22.5 MB
    traitlets-4.3.2            |   py36h674d592_0         131 KB
    pickleshare-0.7.4          |   py36h63277f8_0          11 KB
    libxml2-2.9.7              |       h26e45fe_0         2.0 MB
    jinja2-2.10                |   py36ha16c418_0         184 KB
    nbconvert-5.3.1            |   py36hb41ffb7_0         398 KB
    pyzmq-16.0.3               |   py36he2533c7_0         430 KB
    ipywidgets-7.1.2           |           py36_0          96 KB
    glib-2.53.6                |       h5d9569c_2         8.4 MB
    jupyter-1.0.0              |           py36_4           5 KB
    simplegeneric-0.8.1        |           py36_2           9 KB
    sip-4.18.1                 |   py36h51ed4ed_2         277 KB
    webencodings-0.5.1         |   py36h800622e_1          19 KB
    parso-0.1.1                |   py36h35f843b_0         118 KB
    freetype-2.8               |       hab7d2ae_1         804 KB
    ipython-6.2.1              |   py36h88c514a_1         1.0 MB
    zeromq-4.2.2               |       hbedb6e5_2         662 KB
    testpath-0.3.1             |   py36h8cadb63_0          89 KB
    jedi-0.11.1                |           py36_0         306 KB
    nbformat-4.4.0             |   py36h31c9010_0         137 KB
    qtconsole-4.3.1            |   py36h8f73b5b_0         150 KB
    terminado-0.8.1            |           py36_1          21 KB
    libpng-1.6.34              |       hb9fc6fc_0         334 KB
    gst-plugins-base-1.12.4    |       h33fb286_0         4.8 MB
    mistune-0.8.3              |           py36_0          52 KB
    jupyter_client-5.2.2       |           py36_0         124 KB
    python-dateutil-2.6.1      |   py36h88d3b88_1         237 KB
    pcre-8.41                  |       hc27e229_1         251 KB
    markupsafe-1.0             |   py36hd9260cd_1          24 KB
    prompt_toolkit-1.0.15      |   py36h17d85b1_0         339 KB
    ipython_genutils-0.2.0     |   py36hb52b0d5_0          39 KB
    gstreamer-1.12.4           |       hb53b477_0         3.6 MB
    jupyter_console-5.2.0      |   py36he59e554_1          35 KB
    ptyprocess-0.5.2           |   py36h69acd42_0          22 KB
    pandoc-1.19.2.1            |       hea2e7c5_1        17.8 MB
    gmp-6.1.2                  |       h6c8ec71_1         744 KB
    decorator-4.2.1            |           py36_0          15 KB
    expat-2.2.5                |       he0dffb1_0         186 KB
    tornado-5.0                |           py36_0         640 KB
    jsonschema-2.6.0           |   py36h006f8b5_0          62 KB
    qt-5.6.2                   |      hd25b39d_14        44.5 MB
    pygments-2.2.0             |   py36h0d3125c_0         1.3 MB
    jpeg-9b                    |       h024ee3a_2         248 KB
    pexpect-4.4.0              |           py36_0          73 KB
    html5lib-1.0.1             |   py36h2f9c1c0_0         181 KB
    libsodium-1.0.15           |       hf101ebd_0         313 KB
    notebook-5.4.0             |           py36_0         6.6 MB
    dbus-1.12.2                |       hc3f9b76_1         552 KB
    ipykernel-4.8.2            |           py36_0         145 KB
    widgetsnbextension-3.1.4   |           py36_0         1.7 MB
    wcwidth-0.1.7              |   py36hdf4376a_0          25 KB
    entrypoints-0.2.3          |   py36h1aec115_2           9 KB
    jupyter_core-4.4.0         |   py36h7c827e3_0          61 KB
    libxcb-1.12                |       hcd93eb1_4         446 KB
    bleach-2.1.3               |           py36_0          33 KB
    pyqt-5.6.0                 |   py36h0386399_5         5.5 MB
    pandocfilters-1.4.2        |   py36ha6701b7_1          12 KB
    fontconfig-2.12.4          |       h88586e7_1         282 KB
    ------------------------------------------------------------
                                           Total:       128.9 MB

The following NEW packages will be INSTALLED:

    bleach:             2.1.3-py36_0         
    dbus:               1.12.2-hc3f9b76_1    
    decorator:          4.2.1-py36_0         
    entrypoints:        0.2.3-py36h1aec115_2 
    expat:              2.2.5-he0dffb1_0     
    fontconfig:         2.12.4-h88586e7_1    
    freetype:           2.8-hab7d2ae_1       
    glib:               2.53.6-h5d9569c_2    
    gmp:                6.1.2-h6c8ec71_1     
    gst-plugins-base:   1.12.4-h33fb286_0    
    gstreamer:          1.12.4-hb53b477_0    
    html5lib:           1.0.1-py36h2f9c1c0_0 
    icu:                58.2-h9c2bf20_1      
    ipykernel:          4.8.2-py36_0         
    ipython:            6.2.1-py36h88c514a_1 
    ipython_genutils:   0.2.0-py36hb52b0d5_0 
    ipywidgets:         7.1.2-py36_0         
    jedi:               0.11.1-py36_0        
    jinja2:             2.10-py36ha16c418_0  
    jpeg:               9b-h024ee3a_2        
    jsonschema:         2.6.0-py36h006f8b5_0 
    jupyter:            1.0.0-py36_4         
    jupyter_client:     5.2.2-py36_0         
    jupyter_console:    5.2.0-py36he59e554_1 
    jupyter_core:       4.4.0-py36h7c827e3_0 
    libpng:             1.6.34-hb9fc6fc_0    
    libsodium:          1.0.15-hf101ebd_0    
    libxcb:             1.12-hcd93eb1_4      
    libxml2:            2.9.7-h26e45fe_0     
    markupsafe:         1.0-py36hd9260cd_1   
    mistune:            0.8.3-py36_0         
    nbconvert:          5.3.1-py36hb41ffb7_0 
    nbformat:           4.4.0-py36h31c9010_0 
    notebook:           5.4.0-py36_0         
    pandoc:             1.19.2.1-hea2e7c5_1  
    pandocfilters:      1.4.2-py36ha6701b7_1 
    parso:              0.1.1-py36h35f843b_0 
    pcre:               8.41-hc27e229_1      
    pexpect:            4.4.0-py36_0         
    pickleshare:        0.7.4-py36h63277f8_0 
    prompt_toolkit:     1.0.15-py36h17d85b1_0
    ptyprocess:         0.5.2-py36h69acd42_0 
    pygments:           2.2.0-py36h0d3125c_0 
    pyqt:               5.6.0-py36h0386399_5 
    python-dateutil:    2.6.1-py36h88d3b88_1 
    pyzmq:              16.0.3-py36he2533c7_0
    qt:                 5.6.2-hd25b39d_14    
    qtconsole:          4.3.1-py36h8f73b5b_0 
    send2trash:         1.5.0-py36_0         
    simplegeneric:      0.8.1-py36_2         
    sip:                4.18.1-py36h51ed4ed_2
    terminado:          0.8.1-py36_1         
    testpath:           0.3.1-py36h8cadb63_0 
    tornado:            5.0-py36_0           
    traitlets:          4.3.2-py36h674d592_0 
    wcwidth:            0.1.7-py36hdf4376a_0 
    webencodings:       0.5.1-py36h800622e_1 
    widgetsnbextension: 3.1.4-py36_0         
    zeromq:             4.2.2-hbedb6e5_2     

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 45, in <module>
    ioloop.install()
  File "/opt/conda/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 210, in install
    assert (not ioloop.IOLoop.initialized()) or \
AttributeError: type object 'IOLoop' has no attribute 'initialized'
```
Note that updating `conda` as requested does not help.

**Comment by kalefranz** [comment]
This appears to come from the portion of your command

    /opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='*' --port=8888 --no-browser

Without more specific information, I don't think the issue is filed in the correct location.
