### ISSUE TITLE
conda-build archive_errno AttributeError with continuumio/miniconda3

### ISSUE THREAD

**Issue by matthewgilbert** [ContinuumIO/docker-images#95]
When I install `conda-build` in `continuumio/miniconda3` with either `python=3.6` or `python=3.7` I get runtime errors when using `conda-build`.
```bash
matthew@xps$ docker run -it  continuumio/miniconda3
(base) root@2ef58eb80815:/# conda create -n py36 conda-build python=3.6
(base) root@338aa09942a2:/# conda activate py36
(py36) root@338aa09942a2:/# conda-build --version
Traceback (most recent call last):
  File "/opt/conda/envs/py36/bin/conda-build", line 7, in <module>
    from conda_build.cli.main_build import main
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 18, in <module>
    import conda_build.api as api
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/conda_build/api.py", line 22, in <module>
    from conda_build.config import Config, get_or_merge_config, DEFAULT_PREFIX_LENGTH as _prefix_length
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/conda_build/config.py", line 17, in <module>
    from .variants import get_default_variant
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/conda_build/variants.py", line 15, in <module>
    from conda_build.utils import ensure_list, trim_empty_keys, get_logger
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/conda_build/utils.py", line 10, in <module>
    import libarchive
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/libarchive/__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/libarchive/entry.py", line 6, in <module>
    from . import ffi
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/libarchive/ffi.py", line 108, in <module>
    errno = ffi('errno', [c_archive_p], c_int)
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/libarchive/ffi.py", line 95, in ffi
    f = getattr(libarchive, 'archive_'+name)
  File "/opt/conda/envs/py36/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/opt/conda/envs/py36/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /opt/conda/envs/py36/bin/python: undefined symbol: archive_errno

```

**Comment by mingwandroid** [comment]
Please show the details from the issues template at https://github.com/ContinuumIO/anaconda-issues/issues/new

I suspect you are using some `conda-forge` packages here?

**Comment by mingwandroid** [comment]
Hmm, scratch that, I can reproduce this, investigating now.

**Comment by mingwandroid** [comment]
This is fixed now. Thanks for the bug report.
