### ISSUE TITLE
"libcrypto.so.1.0.0: cannot open shared object file: No such file or directory" when building tensorflow-1.11.0-py27_0.tar.bz2

### ISSUE THREAD

**Issue by ashahba** [ContinuumIO/docker-images#98]
I'm trying to build `tensorflow-1.11.0-py27_0.tar.bz2` for [Intel](https://anaconda.org/intel) channel, which passed using the same recipe many times since last week, but today I'm getting:

``` 
Traceback (most recent call last):
  File "/opt/conda/envs/py2.7/bin/conda-build", line 7, in <module>
    from conda_build.cli.main_build import main
  File "/opt/conda/envs/py2.7/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 18, in <module>
    import conda_build.api as api
  File "/opt/conda/envs/py2.7/lib/python2.7/site-packages/conda_build/api.py", line 22, in <module>
    from conda_build.config import Config, get_or_merge_config, DEFAULT_PREFIX_LENGTH as _prefix_length
  File "/opt/conda/envs/py2.7/lib/python2.7/site-packages/conda_build/config.py", line 15, in <module>
    from .conda_interface import root_dir, root_writable
  File "/opt/conda/envs/py2.7/lib/python2.7/site-packages/conda_build/conda_interface.py", line 36, in <module>
    from conda.exports import display_actions, execute_actions, execute_plan, install_actions
  File "/opt/conda/envs/py2.7/lib/python2.7/site-packages/conda/exports.py", line 14, in <module>
    from . import compat, plan  # NOQA
  File "/opt/conda/envs/py2.7/lib/python2.7/site-packages/conda/plan.py", line 21, in <module>
    from .core.index import LAST_CHANNEL_URLS, _supplement_index_with_prefix
  File "/opt/conda/envs/py2.7/lib/python2.7/site-packages/conda/core/index.py", line 7, in <module>
    from .package_cache_data import PackageCacheData
  File "/opt/conda/envs/py2.7/lib/python2.7/site-packages/conda/core/package_cache_data.py", line 13, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/opt/conda/envs/py2.7/lib/python2.7/site-packages/conda/core/path_actions.py", line 25, in <module>
    from ..gateways.connection.download import download
  File "/opt/conda/envs/py2.7/lib/python2.7/site-packages/conda/gateways/connection/__init__.py", line 5, in <module>
    from requests import ConnectionError, HTTPError, Session
  File "/opt/conda/envs/py2.7/lib/python2.7/site-packages/requests/__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/opt/conda/envs/py2.7/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/opt/conda/envs/py2.7/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/opt/conda/envs/py2.7/lib/python2.7/site-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/opt/conda/envs/py2.7/lib/python2.7/site-packages/OpenSSL/_util.py", line 7, in <module>
    binding = Binding()
  File "/opt/conda/envs/py2.7/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 89, in __init__
    self._ensure_ffi_initialized()
  File "/opt/conda/envs/py2.7/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 109, in _ensure_ffi_initialized
    libraries=libraries,
  File "/opt/conda/envs/py2.7/lib/python2.7/site-packages/cryptography/hazmat/bindings/utils.py", line 80, in build_ffi
    extra_link_args=extra_link_args,
  File "/opt/conda/envs/py2.7/lib/python2.7/site-packages/cffi/api.py", line 451, in verify
    lib = self.verifier.load_library()
  File "/opt/conda/envs/py2.7/lib/python2.7/site-packages/cffi/verifier.py", line 105, in load_library
    return self._load_library()
  File "/opt/conda/envs/py2.7/lib/python2.7/site-packages/cffi/verifier.py", line 216, in _load_library
    return self._vengine.load_library()
  File "/opt/conda/envs/py2.7/lib/python2.7/site-packages/cffi/vengine_cpy.py", line 159, in load_library
    raise VerificationError(error)
cffi.error.VerificationError: importing '/opt/conda/envs/py2.7/lib/python2.7/site-packages/cryptography/_Cryptography_cffi_4ed9e37dx4000d087.so': libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
```

I have 5 environments and sure enough:
```
# conda env list
# conda environments:
#
base                  *  /opt/conda
py2.7                    /opt/conda/envs/py2.7
py3.4                    /opt/conda/envs/py3.4
py3.5                    /opt/conda/envs/py3.5
py3.6                    /opt/conda/envs/py3.6
py3.7                    /opt/conda/envs/py3.7

(base) root@65544d4f3fb1:/tmp/v1.11.0# find / -name libcrypto.so.1.0.0
/opt/conda/envs/py3.6/lib/libcrypto.so.1.0.0
/opt/conda/envs/py3.6/pkgs/openssl-1.0.2o-3/lib/libcrypto.so.1.0.0
/opt/conda/envs/py3.4/lib/libcrypto.so.1.0.0
/opt/conda/envs/py3.4/pkgs/openssl-1.0.2o-3/lib/libcrypto.so.1.0.0
/opt/conda/envs/py3.5/lib/libcrypto.so.1.0.0
/opt/conda/envs/py3.5/pkgs/openssl-1.0.2o-intel_0/lib/libcrypto.so.1.0.0
/opt/conda/envs/py3.7/lib/libcrypto.so.1.0.0
/opt/conda/pkgs/openssl-1.0.2p-h14c3975_0/lib/libcrypto.so.1.0.0
/opt/conda/lib/libcrypto.so.1.0.0
```
So the shared object is missing for `Python 2.7`.

My `meta.yaml` is pretty straight forward and looks like:
```
# cat py2.7_avx/meta.yaml 
{% set version = "1.11.0" %}
{% set buildnumber = 0 %}

package:
  name: tensorflow
  version: {{version}}

build:
  script_env:
    - TF_WHL
  number: {{buildnumber}}
  script: pip install --no-deps {{TF_WHL}}

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pip
    - absl-py >=0.1.6
    - astor >=0.6.0
    - backports.weakref >=1.0rc1
    - enum34 >=1.1.6
    - gast >=0.2.0
    - grpcio >=1.8.6
    - keras-applications >=1.0.5
    - keras-preprocessing >=1.0.3
    - mock >=2.0.0
    - numpy >=1.13.3
    - protobuf >=3.6.0
    - setuptools <=39.1.0
    - six >=1.10.0
    - tensorboard >=1.11.0,<1.12.0
    - termcolor >=1.1.0
    - wheel

about:
  home: http://tensorflow.org/
  license: Apache 2.0
  license_family: Apache
  summary: TensorFlow is a machine learning library
  description: |
    TensorFlow provides multiple APIs.The lowest level API, TensorFlow Core
    provides you with complete programming control.
  dev_url: https://github.com/tensorflow/tensorflow
  doc_url: https://www.tensorflow.org/get_started/get_started
  doc_source_url: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/docs_src
```

I building these using this image Docker image `continuumio/anaconda3:5.3.0` but it looks like the image was changed yesterday which is possibly causing this failure https://hub.docker.com/r/continuumio/anaconda3/tags/

**Comment by jjhelmus** [comment]
@ashahba Could you provide the output of `conda list -n py2.7`?  The list of packages in that environment would make replication and debugging this issue much easier.

**Comment by ashahba** [comment]
@jjhelmus here is what I have:
```
(py2.7) root@a5c0f24e921a:/tmp/v1.11.0# conda list -n py2.7
# packages in environment at /opt/conda/envs/py2.7:
#
# Name                    Version                   Build  Channel
anaconda-client           1.7.2                    py27_0  
backports                 1.0                      py27_1  
backports.functools_lru_cache 1.5                      py27_1  
beautifulsoup4            4.6.3                    py27_0  
bzip2                     1.0.6                h14c3975_5  
ca-certificates           2018.03.07                    0  
certifi                   2018.10.15               py27_0  
cffi                      1.11.5           py27he75722e_1  
chardet                   3.0.4                    py27_1  
click                     7.0                      py27_0  
clyent                    1.2.2                    py27_1  
conda                     4.5.2                    py27_0  
conda-build               3.16.2                   py27_0  
conda-env                 2.6.0                         1  
conda-verify              3.1.1                    py27_0  
contextlib2               0.5.5                    py27_0  
cryptography              0.5.4                    py27_0  
decorator                 4.3.0                    py27_0  
enum34                    1.1.6                    py27_1  
filelock                  3.0.9                    py27_0  
functools32               3.2.3.2                  py27_1  
future                    0.16.0                   py27_2  
futures                   3.2.0                    py27_0  
glob2                     0.6                      py27_1  
icu                       58.2                 h9c2bf20_1  
ipython_genutils          0.2.0                    py27_0  
jinja2                    2.10                     py27_0  
jsonschema                2.6.0                    py27_0  
jupyter_core              4.4.0                    py27_0  
libarchive                3.3.3                h5d8350f_2  
libedit                   3.1.20170329         h6b74fdf_2  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 8.2.0                hdf63c60_1  
libstdcxx-ng              8.2.0                hdf63c60_1  
libxml2                   2.9.8                h26e45fe_1  
lz4-c                     1.8.1.2              h14c3975_0  
lzo                       2.10                 h49e0be7_2  
markupsafe                1.0              py27h14c3975_1  
nbformat                  4.4.0                    py27_0  
ncurses                   6.1                  hf484d3e_0  
openssl                   1.1.1                h7b6447c_0  
patchelf                  0.9                  he6710b0_3  
pip                       10.0.1                   py27_0  
pkginfo                   1.4.2                    py27_1  
psutil                    5.4.7            py27h14c3975_0  
pycosat                   0.6.3            py27h14c3975_0  
pycparser                 2.19                     py27_0  
pyopenssl                 0.15.1                   py27_2  
python                    2.7.15               h9bab390_2  
python-dateutil           2.7.3                    py27_0  
python-libarchive-c       2.8                      py27_6  
pytz                      2018.5                   py27_0  
pyyaml                    3.13             py27h14c3975_0  
readline                  7.0                  h7b6447c_5  
requests                  2.14.2                   py27_0  
ruamel_yaml               0.15.46          py27h14c3975_0  
scandir                   1.9.0            py27h14c3975_0  
setuptools                40.4.3                   py27_0  
six                       1.11.0                   py27_1  
sqlite                    3.25.2               h7b6447c_0  
tk                        8.6.8                hbc83047_0  
tqdm                      4.26.0           py27h28b3542_0  
traitlets                 4.3.2                    py27_0  
wheel                     0.32.2                   py27_0  
xz                        5.2.4                h14c3975_4  
yaml                      0.1.7                had09818_2  
zlib                      1.2.11               ha838bed_2  
zstd                      1.3.3                h84994c4_0
```

**Comment by jjhelmus** [comment]
I believe this issue was caused by the the recent update to openssl 1.1.1 from 1.0.2.  A few packages are still missing compatible builds.  In the listed environment

> cryptography 0.5.4 py27_0

is very old and was likely pulled in because it claims to be compatible with openssl 1.1.1 (in reality it is not).  There are now builds of cryptography 2.3.1 which are compatible with openssl 1.1.1.  @ashahba can you try your builds again, I believe they should work now.

**Comment by ashahba** [comment]
@jjhelmus sounds good.
Let me try and will update here.

**Comment by ashahba** [comment]
This is resolved now so closing the ticket.
